version: "3.9"
services:
  eureka:
    image: beneficio-eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - beneficio
  notifications-service:
    image: notifications-service:0.0.1-SNAPSHOT
    container_name: notifications
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/notifications
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      EUREKA_URL: http://eureka:8761/eureka/
    ports:
      - 8002:8002
    networks:
      - beneficio
    depends_on:
      - postgres
  backend-service:
    image: beneficio:0.0.1-SNAPSHOT
    container_name: backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/backend
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      EUREKA_URL: http://eureka:8761/eureka/
    ports:
      - 8001:8001
    networks:
      - beneficio
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - beneficio
networks:
  beneficio: {}