sse:
  timeout:
    value: 300000
server:
  port: '8002'
  servlet:
    context-path: /j
    application-display-name: notifications
spring:
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: '${DB_URL}'
    password: '${DB_PASSWORD}'
    username: '${DB_USERNAME}'
  application:
    name: notifications
delete:
  readed:
    after:
      days: 6
cron:
  express:
    delete:
      readed: 0 0 23 * * SAT
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
